language: php
php: 7.4
before_install:
  -php /home/travis/.phpenv/versions/7.4.20/composer.phar self-update
before_script: 
  - composer install

script:
 phpunit -- configuration phpunit-xml -- coverage-text

